# Generated by Django 4.0.3 on 2022-03-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('opennings', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('employees', models.IntegerField()),
                ('basic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
