# Generated by Django 4.0.3 on 2022-03-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='corporates',
            table='corporates',
        ),
    ]
